/**
 * 菜单种子数据（266 个菜单项）
 *
 * 包含系统管理、系统监控、系统工具三大模块的完整菜单树，
 * 涵盖按钮级权限（如 system:user:add）。
 *
 * 数据来源：后端 SysMenu 表，4 层嵌套（系统 → 模块 → 子模块 → 操作）
 *
 * @see apps/server/prisma/seed.ts - 使用方式：prisma.sysMenu.createMany({ data: menuData, skipDuplicates: true })
 */

export const menuData = [
      {
        menuId: 1,
        tenantId: '000000',
        menuName: '系统管理',
        parentId: 0,
        orderNum: 1,
        path: 'system',
        component: null,
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'local-icon-menu-system',
        remark: '系统管理目录',
      },
      {
        menuId: 2,
        tenantId: '000000',
        menuName: '系统监控',
        parentId: 0,
        orderNum: 2,
        path: 'monitor',
        component: null,
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'mdi:monitor-dashboard',
        remark: '系统监控目录',
      },
      {
        menuId: 3,
        tenantId: '000000',
        menuName: '系统工具',
        parentId: 0,
        orderNum: 3,
        path: 'tool',
        component: null,
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'local-icon-menu-tool',
        remark: '系统工具目录',
      },
      {
        menuId: 4,
        tenantId: '000000',
        menuName: '项目官网',
        parentId: 0,
        orderNum: 4,
        path: 'https://nest-admin.dooring.vip',
        component: null,
        query: '',
        isFrame: '0',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'guide',
        remark: '项目官网地址',
      },
      {
        menuId: 100,
        tenantId: '000000',
        menuName: '用户管理',
        parentId: 1,
        orderNum: 1,
        path: 'user',
        component: 'system/user/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:user:list',
        icon: 'mdi:account-group-outline',
        remark: '用户管理菜单',
      },
      {
        menuId: 101,
        tenantId: '000000',
        menuName: '角色管理',
        parentId: 1,
        orderNum: 2,
        path: 'role',
        component: 'system/role/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:role:list',
        icon: 'mdi:shield-account-outline',
        remark: '角色管理菜单',
      },
      {
        menuId: 102,
        tenantId: '000000',
        menuName: '菜单管理',
        parentId: 1,
        orderNum: 3,
        path: 'menu',
        component: 'system/menu/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:menu:list',
        icon: 'local-icon-menu-tree-table',
        remark: '菜单管理菜单',
      },
      {
        menuId: 103,
        tenantId: '000000',
        menuName: '部门管理',
        parentId: 1,
        orderNum: 4,
        path: 'dept',
        component: 'system/dept/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:dept:list',
        icon: 'mdi:office-building-outline',
        remark: '部门管理菜单',
      },
      {
        menuId: 104,
        tenantId: '000000',
        menuName: '岗位管理',
        parentId: 1,
        orderNum: 5,
        path: 'post',
        component: 'system/post/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:post:list',
        icon: 'mdi:briefcase-outline',
        remark: '岗位管理菜单',
      },
      {
        menuId: 105,
        tenantId: '000000',
        menuName: '字典管理',
        parentId: 1,
        orderNum: 6,
        path: 'dict',
        component: 'system/dict/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:dict:list',
        icon: 'mdi:book-open-outline',
        remark: '字典管理菜单',
      },
      {
        menuId: 106,
        tenantId: '000000',
        menuName: '参数设置',
        parentId: 1,
        orderNum: 7,
        path: 'config',
        component: 'system/config/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:config:list',
        icon: 'mdi:cog-outline',
        remark: '参数设置菜单',
      },
      {
        menuId: 107,
        tenantId: '000000',
        menuName: '通知公告',
        parentId: 1,
        orderNum: 8,
        path: 'notice',
        component: 'system/notice/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:notice:list',
        icon: 'mdi:bell-outline',
        remark: '通知公告菜单',
      },
      {
        menuId: 118,
        tenantId: '000000',
        menuName: '租户管理',
        parentId: 1,
        orderNum: 9,
        path: 'tenant',
        component: 'system/tenant/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:tenant:list',
        icon: 'mdi:domain',
        remark: '租户管理菜单',
      },
      {
        menuId: 119,
        tenantId: '000000',
        menuName: '租户套餐管理',
        parentId: 1,
        orderNum: 10,
        path: 'tenant-package',
        component: 'system/tenant-package/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:tenantPackage:list',
        icon: 'mdi:package-variant',
        remark: '租户套餐管理菜单',
      },
      {
        menuId: 120,
        tenantId: '000000',
        menuName: '文件管理',
        parentId: 1,
        orderNum: 11,
        path: 'file-manager',
        component: 'system/file-manager/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:file:list',
        icon: 'mdi:folder-multiple-outline',
        remark: '文件管理菜单',
      },
      {
        menuId: 108,
        tenantId: '000000',
        menuName: '日志管理',
        parentId: 1,
        orderNum: 9,
        path: 'log',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'mdi:file-document-outline',
        remark: '日志管理菜单',
      },
      {
        menuId: 109,
        tenantId: '000000',
        menuName: '在线用户',
        parentId: 2,
        orderNum: 1,
        path: 'online',
        component: 'monitor/online/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:online:list',
        icon: 'mdi:account-group',
        remark: '在线用户菜单',
      },
      {
        menuId: 110,
        tenantId: '000000',
        menuName: '定时任务',
        parentId: 2,
        orderNum: 2,
        path: 'job',
        component: 'monitor/job/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:job:list',
        icon: 'mdi:clock-time-eight-outline',
        remark: '定时任务菜单',
      },
      {
        menuId: 112,
        tenantId: '000000',
        menuName: '服务监控',
        parentId: 2,
        orderNum: 4,
        path: 'server',
        component: 'monitor/server/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:server:list',
        icon: 'mdi:server',
        remark: '服务监控菜单',
      },
      {
        menuId: 113,
        tenantId: '000000',
        menuName: '缓存监控',
        parentId: 2,
        orderNum: 5,
        path: 'cache',
        component: 'monitor/cache/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:cache:list',
        icon: 'mdi:database-cog-outline',
        remark: '缓存监控菜单',
      },
      {
        menuId: 114,
        tenantId: '000000',
        menuName: '缓存列表',
        parentId: 2,
        orderNum: 6,
        path: 'cacheList',
        component: 'monitor/cache/list',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:cache:list',
        icon: 'mdi:format-list-bulleted',
        remark: '缓存列表菜单',
      },
      {
        menuId: 115,
        tenantId: '000000',
        menuName: '表单构建',
        parentId: 3,
        orderNum: 1,
        path: 'build',
        component: 'tool/build/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'tool:build:list',
        icon: 'mdi:hammer-wrench',
        remark: '表单构建菜单',
      },
      {
        menuId: 116,
        tenantId: '000000',
        menuName: '代码生成',
        parentId: 3,
        orderNum: 2,
        path: 'gen',
        component: 'tool/gen/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'tool:gen:list',
        icon: 'local-icon-menu-code',
        remark: '代码生成菜单',
      },
      {
        menuId: 117,
        tenantId: '000000',
        menuName: '系统接口',
        parentId: 3,
        orderNum: 3,
        path: 'swagger',
        component: 'tool/swagger/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'tool:swagger:list',
        icon: 'mdi:api',
        remark: '系统接口菜单',
      },
      {
        menuId: 500,
        tenantId: '000000',
        menuName: '操作日志',
        parentId: 108,
        orderNum: 1,
        path: 'operlog',
        component: 'monitor/operlog/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:operlog:list',
        icon: 'mdi:file-document-edit-outline',
        remark: '操作日志菜单',
      },
      {
        menuId: 501,
        tenantId: '000000',
        menuName: '登录日志',
        parentId: 108,
        orderNum: 2,
        path: 'logininfor',
        component: 'monitor/logininfor/index',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:list',
        icon: 'mdi:login',
        remark: '登录日志菜单',
      },
      {
        menuId: 1000,
        tenantId: '000000',
        menuName: '用户查询',
        parentId: 100,
        orderNum: 1,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1001,
        tenantId: '000000',
        menuName: '用户新增',
        parentId: 100,
        orderNum: 2,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:add',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1002,
        tenantId: '000000',
        menuName: '用户修改',
        parentId: 100,
        orderNum: 3,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1003,
        tenantId: '000000',
        menuName: '用户删除',
        parentId: 100,
        orderNum: 4,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1004,
        tenantId: '000000',
        menuName: '用户导出',
        parentId: 100,
        orderNum: 5,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:export',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1005,
        tenantId: '000000',
        menuName: '用户导入',
        parentId: 100,
        orderNum: 6,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:import',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1006,
        tenantId: '000000',
        menuName: '重置密码',
        parentId: 100,
        orderNum: 7,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:resetPwd',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1007,
        tenantId: '000000',
        menuName: '角色查询',
        parentId: 101,
        orderNum: 1,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1008,
        tenantId: '000000',
        menuName: '角色新增',
        parentId: 101,
        orderNum: 2,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:add',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1009,
        tenantId: '000000',
        menuName: '角色修改',
        parentId: 101,
        orderNum: 3,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1010,
        tenantId: '000000',
        menuName: '角色删除',
        parentId: 101,
        orderNum: 4,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1011,
        tenantId: '000000',
        menuName: '角色导出',
        parentId: 101,
        orderNum: 5,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:export',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1012,
        tenantId: '000000',
        menuName: '菜单查询',
        parentId: 102,
        orderNum: 1,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:menu:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1013,
        tenantId: '000000',
        menuName: '菜单新增',
        parentId: 102,
        orderNum: 2,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:menu:add',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1014,
        tenantId: '000000',
        menuName: '菜单修改',
        parentId: 102,
        orderNum: 3,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:menu:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1015,
        tenantId: '000000',
        menuName: '菜单删除',
        parentId: 102,
        orderNum: 4,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:menu:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1016,
        tenantId: '000000',
        menuName: '部门查询',
        parentId: 103,
        orderNum: 1,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dept:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1017,
        tenantId: '000000',
        menuName: '部门新增',
        parentId: 103,
        orderNum: 2,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dept:add',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1018,
        tenantId: '000000',
        menuName: '部门修改',
        parentId: 103,
        orderNum: 3,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dept:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1019,
        tenantId: '000000',
        menuName: '部门删除',
        parentId: 103,
        orderNum: 4,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dept:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1020,
        tenantId: '000000',
        menuName: '岗位查询',
        parentId: 104,
        orderNum: 1,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1021,
        tenantId: '000000',
        menuName: '岗位新增',
        parentId: 104,
        orderNum: 2,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:add',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1022,
        tenantId: '000000',
        menuName: '岗位修改',
        parentId: 104,
        orderNum: 3,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1023,
        tenantId: '000000',
        menuName: '岗位删除',
        parentId: 104,
        orderNum: 4,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1024,
        tenantId: '000000',
        menuName: '岗位导出',
        parentId: 104,
        orderNum: 5,
        path: '',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:export',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1025,
        tenantId: '000000',
        menuName: '字典查询',
        parentId: 105,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1026,
        tenantId: '000000',
        menuName: '字典新增',
        parentId: 105,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:add',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1027,
        tenantId: '000000',
        menuName: '字典修改',
        parentId: 105,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1028,
        tenantId: '000000',
        menuName: '字典删除',
        parentId: 105,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1029,
        tenantId: '000000',
        menuName: '字典导出',
        parentId: 105,
        orderNum: 5,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:export',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1030,
        tenantId: '000000',
        menuName: '参数查询',
        parentId: 106,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1031,
        tenantId: '000000',
        menuName: '参数新增',
        parentId: 106,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:add',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1032,
        tenantId: '000000',
        menuName: '参数修改',
        parentId: 106,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1033,
        tenantId: '000000',
        menuName: '参数删除',
        parentId: 106,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1034,
        tenantId: '000000',
        menuName: '参数导出',
        parentId: 106,
        orderNum: 5,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:export',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1035,
        tenantId: '000000',
        menuName: '公告查询',
        parentId: 107,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:notice:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1036,
        tenantId: '000000',
        menuName: '公告新增',
        parentId: 107,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:notice:add',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1037,
        tenantId: '000000',
        menuName: '公告修改',
        parentId: 107,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:notice:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1038,
        tenantId: '000000',
        menuName: '公告删除',
        parentId: 107,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:notice:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1039,
        tenantId: '000000',
        menuName: '操作查询',
        parentId: 500,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:operlog:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1040,
        tenantId: '000000',
        menuName: '操作删除',
        parentId: 500,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:operlog:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1041,
        tenantId: '000000',
        menuName: '日志导出',
        parentId: 500,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:operlog:export',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1042,
        tenantId: '000000',
        menuName: '登录查询',
        parentId: 501,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1043,
        tenantId: '000000',
        menuName: '登录删除',
        parentId: 501,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1044,
        tenantId: '000000',
        menuName: '日志导出',
        parentId: 501,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:export',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1045,
        tenantId: '000000',
        menuName: '账户解锁',
        parentId: 501,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:unlock',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1046,
        tenantId: '000000',
        menuName: '在线查询',
        parentId: 109,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:online:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1047,
        tenantId: '000000',
        menuName: '批量强退',
        parentId: 109,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:online:batchLogout',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1048,
        tenantId: '000000',
        menuName: '单条强退',
        parentId: 109,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:online:forceLogout',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1049,
        tenantId: '000000',
        menuName: '任务查询',
        parentId: 110,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:job:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1050,
        tenantId: '000000',
        menuName: '任务新增',
        parentId: 110,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:job:add',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1051,
        tenantId: '000000',
        menuName: '任务修改',
        parentId: 110,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:job:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1052,
        tenantId: '000000',
        menuName: '任务删除',
        parentId: 110,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:job:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1053,
        tenantId: '000000',
        menuName: '状态修改',
        parentId: 110,
        orderNum: 5,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:job:changeStatus',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1054,
        tenantId: '000000',
        menuName: '任务导出',
        parentId: 110,
        orderNum: 6,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:job:export',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1055,
        tenantId: '000000',
        menuName: '生成查询',
        parentId: 116,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1056,
        tenantId: '000000',
        menuName: '生成修改',
        parentId: 116,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1057,
        tenantId: '000000',
        menuName: '生成删除',
        parentId: 116,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1058,
        tenantId: '000000',
        menuName: '导入代码',
        parentId: 116,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:import',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1059,
        tenantId: '000000',
        menuName: '预览代码',
        parentId: 116,
        orderNum: 5,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:preview',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1060,
        tenantId: '000000',
        menuName: '生成代码',
        parentId: 116,
        orderNum: 6,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:code',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1061,
        tenantId: '000000',
        menuName: '租户查询',
        parentId: 118,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenant:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1062,
        tenantId: '000000',
        menuName: '租户新增',
        parentId: 118,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenant:add',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1063,
        tenantId: '000000',
        menuName: '租户修改',
        parentId: 118,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenant:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1064,
        tenantId: '000000',
        menuName: '租户删除',
        parentId: 118,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenant:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1065,
        tenantId: '000000',
        menuName: '租户导出',
        parentId: 118,
        orderNum: 5,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenant:export',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1066,
        tenantId: '000000',
        menuName: '租户套餐查询',
        parentId: 119,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenantPackage:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1067,
        tenantId: '000000',
        menuName: '租户套餐新增',
        parentId: 119,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenantPackage:add',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1068,
        tenantId: '000000',
        menuName: '租户套餐修改',
        parentId: 119,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenantPackage:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1069,
        tenantId: '000000',
        menuName: '租户套餐删除',
        parentId: 119,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenantPackage:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1070,
        tenantId: '000000',
        menuName: '租户套餐导出',
        parentId: 119,
        orderNum: 5,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenantPackage:export',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1071,
        tenantId: '000000',
        menuName: '文件查询',
        parentId: 120,
        orderNum: 1,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:file:query',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1072,
        tenantId: '000000',
        menuName: '文件新增',
        parentId: 120,
        orderNum: 2,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:file:add',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1073,
        tenantId: '000000',
        menuName: '文件编辑',
        parentId: 120,
        orderNum: 3,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:file:edit',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1074,
        tenantId: '000000',
        menuName: '文件删除',
        parentId: 120,
        orderNum: 4,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:file:remove',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1075,
        tenantId: '000000',
        menuName: '文件分享',
        parentId: 120,
        orderNum: 5,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:file:share',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1076,
        tenantId: '000000',
        menuName: '回收站列表',
        parentId: 120,
        orderNum: 6,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:file:recycle:list',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1077,
        tenantId: '000000',
        menuName: '回收站恢复',
        parentId: 120,
        orderNum: 7,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:file:recycle:restore',
        icon: '#',
        remark: '',
      },
      {
        menuId: 1078,
        tenantId: '000000',
        menuName: '回收站删除',
        parentId: 120,
        orderNum: 8,
        path: '#',
        component: '',
        query: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:file:recycle:remove',
        icon: '#',
        remark: '',
      },
];
