/**
 * Phase 3: Merge Services
 *
 * Analyzes service files that need merging.
 * This script generates a MERGE_PLAN.md showing what would be merged.
 *
 * Run: npx tsx scripts/refactor/merge-services.ts
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = '/Users/mac/Documents/project/nest-admin/apps/server/src';

interface ServiceInfo {
  module: string;
  files: string[];
  mainFile: string | null;
  totalLines: number;
}

function countLines(file: string): number {
  try {
    return readFileSync(file, 'utf-8').split('\n').length;
  } catch {
    return 0;
  }
}

function findServices(dir: string, depth = 0): ServiceInfo[] {
  const results: ServiceInfo[] = [];

  if (depth > 3) return results;

  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (!statSync(fullPath).isDirectory()) continue;

    // Check for services/ subdirectory
    const servicesDir = join(fullPath, 'services');
    if (statSync(servicesDir).isDirectory()) {
      const files = readdirSync(servicesDir)
        .filter((f) => f.endsWith('.service.ts'))
        .map((f) => join(servicesDir, f));

      const mainService = join(fullPath, `${entry.replace(/-/g, '')}.service.ts`);
      const hasMain = statSync(mainService).isFile();

      results.push({
        module: entry,
        files,
        mainFile: hasMain ? mainService : null,
        totalLines: files.reduce((s, f) => s + countLines(f), 0) + (hasMain ? countLines(mainService) : 0),
      });
    }

    results.push(...findServices(fullPath, depth + 1));
  }

  return results;
}

// Find the current user module
const userModulePath = join(ROOT, 'modules', 'users');
const mainServicePath = join(userModulePath, 'users.service.ts');
const servicesDir = join(userModulePath, 'services');

console.log('\n=== Service Merge Analysis ===\n');

let hasUsersService = false;
let hasServicesDir = false;

try {
  statSync(mainServicePath);
  hasUsersService = true;
} catch {}

try {
  statSync(servicesDir);
  hasServicesDir = true;
} catch {}

if (hasServicesDir) {
  const serviceFiles = readdirSync(servicesDir).filter((f) => f.endsWith('.service.ts'));
  console.log(`Found ${serviceFiles.length} service files in modules/users/services/:`);
  for (const f of serviceFiles) {
    const lines = countLines(join(servicesDir, f));
    console.log(`  - ${f} (${lines} lines)`);
  }
}

if (hasUsersService) {
  const lines = countLines(mainServicePath);
  console.log(`\nFound main users.service.ts: ${lines} lines`);
}

const modulesDir = join(ROOT, 'modules');
let hasModulesDir = false;
try {
  statSync(modulesDir);
  hasModulesDir = true;
} catch {}

if (!hasModulesDir) {
  console.log('\n⚠ modules/ directory not found yet. Run move-files.ts first.\n');
  process.exit(0);
}

const allServices = findServices(modulesDir);

console.log('\n=== All modules with services/ subdirectories ===\n');
for (const s of allServices) {
  console.log(`\nModule: ${s.module}`);
  console.log(`  Files: ${s.files.length} service files`);
  for (const f of s.files) {
    const lines = countLines(f);
    console.log(`    ${f.split('/').pop()} (${lines} lines)`);
  }
  if (s.mainFile) {
    console.log(`  Main: ${s.mainFile.split('/').pop()} (${countLines(s.mainFile)} lines)`);
  }
  console.log(`  Total: ${s.totalLines} lines`);
}

// Generate merge plan
const mergePlan: string[] = [];
mergePlan.push('# Service Merge Plan\n');
mergePlan.push(`Generated: ${new Date().toISOString()}\n\n`);

for (const s of allServices) {
  mergePlan.push(`## ${s.module}\n`);
  mergePlan.push(`**Total lines**: ${s.totalLines}\n\n`);

  mergePlan.push('### Files to merge\n');
  for (const f of s.files) {
    mergePlan.push(`- \`${f.split('/').pop()}\` (${countLines(f)} lines)\n`);
  }
  if (s.mainFile) {
    mergePlan.push(`- \`${s.mainFile.split('/').pop()}\` (${countLines(s.mainFile)} lines)\n`);
  }

  mergePlan.push('### Proposed structure\n');
  mergePlan.push('```typescript\n');
  mergePlan.push('@Injectable()\n');
  mergePlan.push(`export class ${s.module.replace(/-/g, '').replace(/^\w/, (c) => c.toUpperCase())}Service {\n`);
  mergePlan.push('  // region: [business capability]\n');
  mergePlan.push('  // ...\n');
  mergePlan.push('  // endregion\n');
  mergePlan.push('}\n');
  mergePlan.push('```\n\n');
}

writeFileSync('/Users/mac/Documents/project/nest-admin/scripts/refactor/SERVICE_MERGE_PLAN.md', mergePlan.join(''));
console.log('\n📄 MERGE_PLAN.md generated\n');

// Merge for the users module specifically
if (hasServicesDir && hasUsersService) {
  console.log('\n=== Generating merged users.service.ts ===\n');

  let mergedContent = `/**
 * Users Service - Merged
 * Generated by refactor script. Review before committing.
 */

// region: Auth
`;

  const authFiles = ['auth.service.ts', 'captcha.service.ts', 'social.service.ts'];
  for (const sf of serviceFiles) {
    const fileName = sf.split('/').pop()!;
    const content = readFileSync(join(servicesDir, sf), 'utf-8');
    const className = content.match(/export class (\w+)/)?.[1];

    if (authFiles.includes(fileName)) {
      mergedContent += `\n// --- ${fileName} ---\n`;
      mergedContent += content;
      mergedContent += '\n';
    }
  }

  mergedContent += `// endregion\n\n// region: Main\n`;

  for (const sf of serviceFiles) {
    const fileName = sf.split('/').pop()!;
    const content = readFileSync(join(servicesDir, sf), 'utf-8');
    if (!authFiles.includes(fileName)) {
      mergedContent += `\n// --- ${fileName} ---\n`;
      mergedContent += content;
      mergedContent += '\n';
    }
  }

  if (hasUsersService) {
    const mainContent = readFileSync(mainServicePath, 'utf-8');
    mergedContent += `\n// --- main users.service.ts ---\n`;
    mergedContent += mainContent;
  }

  mergedContent += '\n// endregion\n';

  const outPath = join(ROOT, 'modules', 'users', 'users.service.ts');
  writeFileSync(outPath, mergedContent);
  console.log(`📄 Written: ${outPath}\n`);
  console.log('⚠ Review the merged file and remove service sub-files manually.\n');
}

console.log('✅ Phase 3 analysis complete.\n');
